/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '28/06/14 10:57 PM' with Gradle 1.12
 *
 * @author MarkPerry, @date 28/06/14 10:57 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
